CarRecognition/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('recognition/', include("recognition.urls")),
    path('statistic/', include("statistic.urls")),
    path('manage/', include("manage.urls")),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("mypage/", views.mypage, name="mypage"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("dismember/", views.dismember, name="dismember"),
    path("search_record/", views.search_record, name="search_record"),
    path("search_record2/", views.search_record2, name = "search_record2")
]

manage/urls.py
from django.urls import path, include
from manage import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'manage'
urlpatterns = [
    path("", views.manage, name="manage"),
    path("reaAllUser/", views.reaAllUser, name="reaAllUser"),
    path("delUser/", views.delUser, name="delUser"),
    path("grantUser/", views.grantUser, name="grantUser"),
    path("<str:id>/delCctv",views.delCctv, name="delCctv"),
    path("uploadcctv/", views.uploadcctv, name="uploadcctv"),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

recognition/urls.py
from django.urls import path
from . import views

app_name = 'recognition'
urlpatterns = [
    path("", views.recognition, name="recognition"),
    path("recog/", views.recog, name='recog'),
    path("recogTime/", views.recogTime, name='recogTime'),
]

home/models.py
from django.db import models
from recognition.models import Cctv
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Profile(models.Model) :
    class MemberPermission(models.TextChoices):
        ADMIN = 'admin'
        MEMBER = 'member'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    permission = models.CharField(MemberPermission.choices, default=MemberPermission.MEMBER, max_length=10)

    class Meta:
        db_table = 'Profile'

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

class UserLog(models.Model) :
    user = models.ForeignKey('auth.User', to_field='username', on_delete=models.CASCADE)
    search_time = models.DateTimeField()
    end_time = models.DateTimeField()
    cctv_id = models.ForeignKey(Cctv, to_field='id', on_delete=models.CASCADE, default='')

    class Meta:
        db_table = "UserLog"

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
from home.models import Profile, UserLog
from recognition.models import CctvLog, Cctv
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import check_password
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.db.models import Q
import datetime

def index(req) :

    user_name = None
    cctv = Cctv.objects.all()
    cctv_list = serializers.serialize('json', cctv)

    if req.user.is_anonymous!=True:
        user_name = Profile.objects.get(user=auth.get_user(req))
        # return HttpResponse(cctv_list)

    if req.method == 'POST':
        return redirect('recognition:recognition')

    return render(req, "index.html", {'user': user_name, 'cctv': cctv_list, 'count': range(cctv.count())})

def login(req):
    cur_user = req.user
    if cur_user.is_authenticated:
        return redirect("home:index")

    if req.method == 'POST':
        username = req.POST['username']
        password = req.POST['password']

        user = auth.authenticate(req, username=username, password=password)

        if user is not None:
            auth.login(req, user)
            return redirect('home:index')
        else:
            messages.info(req, '아이디 혹은 비밀번호가 틀렸습니다.')
            return render(req, "login.html")

    else:
        return render(req, "login.html")

def logout(req):

    auth.logout(req)
    messages.info(req, '로그아웃 되었습니다.')

    return redirect('home:index')

def register(req):
    cur_user = req.user
    if cur_user.is_authenticated:
        return redirect("home:index")

    if req.method == 'POST':
        user_form = UserCreationForm(req.POST)
        if user_form.is_valid():
            user = user_form.save()
            profile = Profile.objects.get(user=user)
            profile.name = req.POST['name']
            profile.save()

            login_id = User.objects.get(username=profile.user.username)
            auth.login(req, login_id)

            messages.info(req, '회원가입이 정상적으로 완료되었습니다.')
            return redirect('home:index')

        else:
            messages.info(req, '중복된 아이디 혹은 비밀번호가 틀렸습니다.')
    else:
        user_form = UserCreationForm()

    return render(req, "register.html", {'user_form':user_form})

def mypage(req):
    cur_user = req.user

    if cur_user.is_authenticated:
        user = Profile.objects.get(user=auth.get_user(req))

        return render(req, "mypage.html", {'user': user})
    else:
        messages.info(req, '로그인 후 이용가능합니다.')
        return redirect("home:index")

def update(req):

    user_name = Profile.objects.get(user=auth.get_user(req))
    context= {'user_name':user_name}

    if req.method == "POST":
        current_password = req.POST.get("origin_password")
        user = req.user
        if check_password(current_password,user.password):
            new_password = req.POST.get("password1")
            password_confirm = req.POST.get("password2")
            if new_password == password_confirm and len(new_password)>8:
                user_name.name = req.POST.get("name")
                user_name.save()
                user.set_password(new_password)
                user.save()
                auth.login(req,user)
                messages.info(req,"정보가 변경 되었습니다.")
                return redirect('home:index')
            elif len(new_password)==0 and len(password_confirm)==0:
                user_name.name = req.POST.get("name")
                user_name.save()
                messages.info(req, "정보가 변경 되었습니다.")
                return redirect('home:index')
            else:
                messages.info(req,"새로운 비밀번호를 확인해 주세요.")
        else:
            messages.info(req,"기존 비밀번호가 일치하지 않습니다.")

    return redirect("home:mypage")

def dismember(req):

    user_name = Profile.objects.get(user=auth.get_user(req))
    context= {'user_name':user_name}

    if req.method == "POST":
        current_password = req.POST.get("password")
        user = req.user

        if check_password(current_password,user.password):
                auth.logout(req)
                user.delete()
                messages.info(req,'탈퇴 처리 되었습니다.')
                return redirect('home:index')
        else:
            messages.info(req,'비밀번호가 일치하지 않습니다.')

    return redirect("home:mypage")

@csrf_exempt
def search_record(req):

    date1 = req.POST.get('date1','')
    date2 = req.POST.get('date2','')

    m1 = int(date1[0:2])
    d1 = int(date1[3:5])
    y1 = int(date1[6:10])
    m2 = int(date2[0:2])
    d2 = int(date2[3:5])
    y2 = int(date2[6:10])

    startdate=datetime.date(y1,m1,d1)
    enddate = datetime.date(y2,m2,d2)

    userlogs = list(UserLog.objects.filter(
        Q(user=auth.get_user(req)) & Q(search_time__gte=startdate, end_time__lte=enddate)).values())

    infolist = []

    for value in userlogs:
        cctv_name = Cctv.objects.get(id = value['cctv_id_id'])
        value['location'] = cctv_name.location
        infolist.append(value)

        datetemp = value['search_time'].strftime("%Y/%m/%d %H:%M:%S")
        value['search_time'] = datetemp
        datetemp2 = value['end_time'].strftime("%Y/%m/%d %H:%M:%S")
        value['end_time'] = datetemp2

    return JsonResponse(infolist, safe=False)


@csrf_exempt
def search_record2(req):

    date1 = req.POST.get('date1','')
    date2 = req.POST.get('date2','')

    m1 = int(date1[0:2])
    d1 = int(date1[3:5])
    y1 = int(date1[6:10])
    m2 = int(date2[0:2])
    d2 = int(date2[3:5])
    y2 = int(date2[6:10])

    startdate=datetime.date(y1,m1,d1)
    enddate = datetime.date(y2,m2,d2)

    userlogs = UserLog.objects.filter(Q(user=auth.get_user(req))&Q(search_time__gte=startdate,end_time__lte=enddate))

    cctvlogs = []
    i = 0

    for userlog in userlogs:
        query = CctvLog.objects.filter(Q(cctv_id=userlog.cctv_id) & Q(appearance_time__gte=userlog.search_time, appearance_time__lte=userlog.end_time))
        log_list = list(query.values())
        for value in log_list:
            datetemp = value['appearance_time'].strftime("%m/%d/%Y %H:%M:%S")
            value['appearance_time'] = datetemp
            cctvlogs.append(value)

    return JsonResponse(cctvlogs, safe=False)

home/templates/footer.html
<footer style="background-color: #F8F8F8">
		<div class="container">
				<br>
				<div class="row">
					<div class="col-sm-3" style="text-align: center;"><h4>Copyright &copy; 2020</h4><h4>커피탄 리 (Captain)</h4></div>
					<div class="col-sm-6" style="text-align: center"><h4>Capston Design Group3</h4><p>( Hwang Ho, Kim Min Chan, Lee Yoon Gu, Yu Ju Hyun, Lee Joong Hoon )</p></div>
					<div class="col-sm-3"><h4 style="text-align: center;"><span class="glyphicon glyphicon-ok"></span>&nbsp;by 커피탄리</h4></div>
                    <br>
				</div>
			</div>
        <br>
</footer>

home/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>커피탄 리</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/button.css' %}">
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
</head>
<body>

<style type="text/css">
    .jumbotron_recog {
        background-image: url( {% static 'images/jumbotronRecog.jpg' %});
        background-size: cover;
        text-shadow: black 0.2em 0.2em 0.2em;
        color: white;
        height: 300px;
        padding: 6%;
    }

    .jumbotron_chart {
        background-image: url({% static 'images/jumbotronChart.jpg' %});
        background-size: cover;
        color: white;
        text-shadow: black 0.2em 0.2em 0.2em;
        height: 300px;
        padding: 6%;
    }

</style>

{% include 'nav.html' %}

<br>
<div class="container">
    <ul class="nav nav-tabs">
        <li class="nav-item active in">

            <a class="nav-link" data-toggle="tab" href="#Recognize"
               style="color: black; font-size:15px; margin-top: 15px">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                인식
            </a>
        </li>

        <li class="nav-item in">
            <a class="nav-link" data-toggle="tab" href="#Statistic"
               style="color: black; font-size:15px; margin-top: 15px">
                <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
                통계
            </a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade active in" id="Recognize" style="width: 100%;">
            <div class="row">
                <div class="jumbotron_recog">
                    <h1 class="text-center">차량 인식 서비스</h1>
                    <p class="text-center">CCTV에 촬영된 차량 분류 및 재식별하는 프로그램입니다.</p>
                    <p class="text-center"><a class="btn btn-lg btn-primary" data-target="#recogModal"
                                              data-toggle="modal" onclick="setlayout();">서비스 시작하기</a></p>
                </div>
            </div>
        </div>

        <div class="tab-pane fade in" id="Statistic" style="width: 100%;">
            <div class="row main">
                <div class="jumbotron_chart">
                    <h1 class="text-center">차량 식별 통계 서비스</h1>
                    <p class="text-center">식별된 차량의 통계를 그래프를 통해 보여줍니다.</p>
                    <p class="text-center"><a class="btn btn-lg btn-primary" data-target="#statisticModal"
                                              data-toggle="modal" onclick="setlayout();">서비스 시작하기</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<br>
<div class="container">
    <div class="col-sm-4">
        <h4>시스템 목적</h4>
        <p>CCTV 상에서 찾고자 하는 차량을 딥러닝 기반 기술로 자동으로 재식별하여 대상이 되는 차량을 빠른 속도로 추적하여 범죄 수사나 차량 추적에 도움이 될 수 있음</p>
    </div>
    <div class="col-sm-4">
        <h4>프로그램 사용법</h4>
        <p>프로그램 사용법은 다음과 같은 순서로 진행합니다.</p>

        <a class="btn btn-default pull-right" href="{% url 'recognition:recognition' %}">더 알아보기</a>
    </div>
    <div class="col-sm-4">
        <h4>서비스</h4>
        <ol>
            <li>인식 서비스</li>
            <li>통계 서비스</li>
        </ol>
    </div>
</div>

<br>
{% include 'recog_modal.html' %}
{% include 'statistic_modal.html' %}
<br><br>
{% include 'footer.html' %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <script>alert("{{ message }}")</script>
        {% endfor %}
    </ul>
{% endif %}

</body>
</html>
<script src="{% static 'vendor/bootstrap/js/bootstrap.js' %}"></script>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=a8a08365e71499493906a12ac8f92432"></script>
<script>

    var recognition_container = document.getElementById('recognition_map');
    var statistic_container = document.getElementById('statistic_map')

    var options = {
        center: new kakao.maps.LatLng(37.549341, 127.0742582),
        level: 3
    };

    var recognition_map = new kakao.maps.Map(recognition_container, options);
    var statistic_map = new kakao.maps.Map(statistic_container, options);

    function setlayout() {
        setTimeout(function () {
                recognition_map.relayout();
                statistic_map.relayout();
            }
            , 0);
    }

    var cctv_obj = "{{ cctv }}".replace(/&quot;/g, '"');
    var cctv_json = JSON.parse(cctv_obj);

    // 마커 이미지의 이미지 주소입니다
    var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png";

    var positions = [
        {% for i in count %}
            {
                title: cctv_json[{{i}}].fields.location,
                latlng: new kakao.maps.LatLng(cctv_json[{{i}}].fields.latitude, cctv_json[{{i}}].fields.longtitude)
            },
        {% endfor %}
    ];

    for (var i = 0; i < positions.length; i++) {

        var imageSize = new kakao.maps.Size(24, 35);

        // 마커를 생성합니다
        var recognition_marker = new kakao.maps.Marker({
            map: recognition_map, // 마커를 표시할 지도
            position: positions[i].latlng, // 마커를 표시할 위치
            title: positions[i].title, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다
            clickable: true
        });

        var statistic_marker = new kakao.maps.Marker({
            map: statistic_map, // 마커를 표시할 지도
            position: positions[i].latlng, // 마커를 표시할 위치
            title: positions[i].title, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다
            clickable: true
        });

        var infowindow = new kakao.maps.InfoWindow({
            content: positions[i].title // 인포윈도우에 표시할 내용
        });

        kakao.maps.event.addListener(recognition_marker, 'click', recognition_get_location(positions[i].title));
        kakao.maps.event.addListener(recognition_marker, 'mouseover', makeOverListener(recognition_map, recognition_marker, infowindow));
        kakao.maps.event.addListener(recognition_marker, 'mouseout', makeOutListener(infowindow));

        kakao.maps.event.addListener(statistic_marker, 'click', statistic_get_location(positions[i].title));
        kakao.maps.event.addListener(statistic_marker, 'mouseover', makeOverListener(statistic_map, statistic_marker, infowindow));
        kakao.maps.event.addListener(statistic_marker, 'mouseout', makeOutListener(infowindow));

    }

    // 인포윈도우를 표시하는 클로저를 만드는 함수입니다
    function makeOverListener(map, marker, infowindow) {
        return function () {
            infowindow.open(map, marker);
        };
    }

    // 인포윈도우를 닫는 클로저를 만드는 함수입니다
    function makeOutListener(infowindow) {
        return function () {
            infowindow.close();
        };
    }

    function recognition_get_location(info) {
        return function () {
            document.getElementById("recognition_location").value = info;
        };
    }

    function statistic_get_location(info) {
        return function () {
            document.getElementById("statistic_location").value = info;
        };
    }

    $(function () {
        $('#recognition_start_time').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            ignoreReadonly: true
        });
    });

    $(function () {
        $('#statistic_start_time').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            ignoreReadonly: true
        });
    });

    $(function () {
        $('#recognition_end_time').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            ignoreReadonly: true
        });
    });

    $(function () {
        $('#statistic_end_time').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            ignoreReadonly: true
        });
    });
</script>

home/templates/login.html
  {% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>커피탄 리 : 로그인</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">

</head>
<body>
<section class="login-form">

    <div style="text-align: center">
        <a class="btn" href="{% url 'home:index' %}">돌아가기</a>
    </div>

    <h1>로그인</h1>
    <form action="/login/" method="POST">
        {% csrf_token %}
        <div class="int-area">
            <input type="text" name="username" id="username" autocomplete="off" required>
            <label for="id">아이디</label>
        </div>
        <div class="int-area">
            <input type="password" name="password" id="password" autocomplete="off" required>
            <label for="pw">비밀번호</label>
        </div>
        <div class="btn-area">
            <button id="btn" type="submit">로그인</button>
        </div>
    </form>

</section>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <script>alert("{{ message }}")</script>
                {% endfor %}
            </ul>
        {% endif %}

<script>
    let id = $('#id');
    let pw = $('#pw');
    let btn = $('#btn');

    $(btn).on('click', function () {
        if ($(id).val() == "") {
            $(id).next('label').addClass('warning');
            setTimeout(function () {
                $('label').removeClass('warning');
            }, 1400);
        } else if ($(pw).val() == "") {
            $(pw).next('label').addClass('warning');
            setTimeout(function () {
                $('label').removeClass('warning');
            }, 1400);
        }
    });
</script>

</body>
</html>
<script src="http://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.js' %}"></script>

home/templates/nav.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css" rel="stylesheet">
<link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">

    <nav class="nav navbar-default">
			<div class="container-fluid">
				<div class="nav-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'home:index' %}">커피탄 리</a>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li><a href="{% url 'home:index' %}">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                            Home
                        </a></li>
						<li><a href="{% url 'recognition:recognition' %}">
                            <span class="glyphicon glyphicon-blackboard" aria-hidden="true"></span>
                            Service
                        </a></li>
					</ul>

                    <ul class="nav navbar-nav navbar-right">
						{% if user == None %}
                        <li><a href="{% url 'home:login' %}">
                            Login
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                        </a></li>

						<li><a href="{% url 'home:register' %}">
                            Register
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        </a></li>

                        {% else %}
                            {% if user.permission  == 'admin' %}
                                <li><a href="{% url 'manage:manage' %}">관리자 페이지
                                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a></li>
                            {% endif %}
                            <li><a href="{% url 'home:mypage' %}">
                                '{{ user.name }}'의 정보
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                            </a></li>

                            <li><a href="{% url 'home:logout' %}">
                                Logout
                                <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                            </a></li>
                        {% endif %}
					</ul>
				</div>
			</div>
		</nav>

home/templates/recog_modal.html
<div class="row">
    <div class="modal" id="recogModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    차량 인식 서비스
                    <button class="close" data-dismiss="modal">&times;</button>
                </div>

                <form action="/recognition/recog/" method="POST">
                    {% csrf_token %}
                    <div class="modal-body" style="width:550px;height:480px;text-align: center;">
                        <div class="col-sm-4">
                            <span style="font-weight: bolder; font-size: 15px;">시작 시간</span>
                            <input id="recognition_start_time" type="text" name="start_time" width="180"
                                   style="margin-bottom: 15px"  required >
                        </div>

                        <div class="col-sm-4">
                            <span style="font-weight: bolder; font-size: 15px;" style="margin-bottom: 15px">종료 시간</span>
                            <input id="recognition_end_time" type="text" name="end_time" width="180"
                                   style="margin-bottom: 15px" required>
                        </div>

                        <div class="col-sm-4">
                            <span style="font-weight: bolder; font-size: 15px;" style="margin-bottom: 15px">위치</span>
                            <input id="recognition_location" name="location" width="180" value=""
                                   style="margin-bottom: 15px"  readonly>
                        </div>

                        <div id="recognition_map" style="width:565px;height:350px;"></div>

                        <div class="btn-area">
                            <button class = base_button id="btn" type="submit" style="margin-top: 10px;width: 150px">제출</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

home/templates/register.html
    {% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>커피탄 리 : 회원가입</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
    <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.js' %}"></script>
</head>
<body>
<section class="login-form">

    <div style="text-align: center">
        <a class="btn" href="{% url 'home:index' %}">돌아가기</a>
    </div>

    <h1>회원가입</h1>
    <form action="/register/" method="post">
        {% csrf_token %}
        <div class="int-area">
            <input type="text" name="username" id="id" autocomplete="off" required>
            <label for="id">아이디</label>
        </div>
        <div class="int-area">
            <input type="password" name="password1" id="password1" autocomplete="off" required>
            <label for="pw">비밀번호</label>
        </div>
        <div class="int-area">
            <input type="password" name="password2" id="password2" autocomplete="off" required>
            <label for="pwChk">비밀번호확인</label>
        </div>
        <div class="int-area">
            <input type="text" name="name" id="name" autocomplete="off" required>
            <label for="name">이름</label>
        </div>
        <div class="btn-area">
            <button id="btn-register" type="submit">회원가입</button>
        </div>
    </form>
</section>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <script>alert("{{ message }}")</script>
                {% endfor %}
            </ul>
        {% endif %}

<script type="text/javascript">
    let id = $('#id');
    let pw = $('#password1');
    let pwChk = $('#password2');
    let name = $('#name');
    let btn = $('#btn-register');

    $(btn).on('click', function () {
        if ($(id).val() == "") {
            $(id).next('label').addClass('warning');
            setTimeout(function () {
                $('label').removeClass('warning');
            }, 1400);
        } else if ($(pw).val() == "") {
            $(pw).next('label').addClass('warning');
            setTimeout(function () {
                $('label').removeClass('warning');
            }, 1400);
        } else if ($(pwChk).val() == "") {
            $(pwChk).next('label').addClass('warning');
            setTimeout(function () {
                $('label').removeClass('warning');
            }, 1400);
        } else if ($(name).val() == "") {
            $(name).next('label').addClass('warning');
            setTimeout(function () {
                $('label').removeClass('warning');
            }, 1400);
        }
    });

</script>
</body>
</html>

home/templates/statistic_modal.html
<div class="row">
    <div class="modal" id="statisticModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    인식 통계 서비스
                    <button class="close" data-dismiss="modal">&times;</button>
                </div>

                <form action="/statistic/stat/" method="POST">
                    {% csrf_token %}
                    <div class="modal-body" style="width:550px;height:480px;text-align: center;">
                        <div class="col-sm-4">
                            <span style="font-weight: bolder; font-size: 15px;">시작 시간</span>
                            <input id="statistic_start_time" type="text" name="start_time" width="180"
                                   style="margin-bottom: 15px" required autocomplete="off">
                        </div>

                        <div class="col-sm-4">
                            <span style="font-weight: bolder; font-size: 15px;" style="margin-bottom: 15px">종료 시간</span>
                            <input id="statistic_end_time" type="text" name="end_time" width="180"
                                   style="margin-bottom: 15px" required autocomplete="off">
                        </div>

                        <div class="col-sm-4">
                            <span style="font-weight: bolder; font-size: 15px;" style="margin-bottom: 15px">위치</span>
                            <input id="statistic_location" name="location" width="180" value=""
                                   style="margin-bottom: 15px" autocomplete="off">
                        </div>

                        <div id="statistic_map" style="width:565px;height:350px;"></div>

                        <div class="btn-area">
                            <button class= base_button id="btn" type="submit" style="width: 150px;margin-top: 10px">제출</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
</div>