CarRecognition/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('recognition/', include("recognition.urls")),
    path('statistic/', include("statistic.urls")),
    path('manage/', include("manage.urls")),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("mypage/", views.mypage, name="mypage"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("dismember/", views.dismember, name="dismember"),
    path("search_record/", views.search_record, name="search_record"),
    path("search_record2/", views.search_record2, name = "search_record2")
]

recognition/urls.py
from django.urls import path
from . import views

app_name = 'recognition'
urlpatterns = [
    path("", views.recognition, name="recognition"),
    path("recog/", views.recog, name='recog'),
    path("recogTime/", views.recogTime, name='recogTime'),
]

statistic/urls.py
from django.urls import path
from . import views

app_name = 'statistic'
urlpatterns = [
    path("", views.statistic, name="statistic"),
    path("stat/", views.stat, name="stat"),
]

statistic/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from home.models import Profile
from django.contrib import auth
from django.contrib import messages
from django.core import serializers
from car.models import Car
from recognition.models import Cctv, CctvLog
from django.db.models import Count, Q
from django.db.models import Subquery


# Create your views here.

def statistic(req):
    cur_user = req.user
    cctv = Cctv.objects.all()
    cctv_list = serializers.serialize('json', cctv)

    if cur_user.is_authenticated:
        user = Profile.objects.get(user=auth.get_user(req))

        return render(req, "statistic_Service.html", {'user': user, 'cctv': cctv_list, 'count': range(cctv.count())})
    else:
        messages.info(req, '로그인 후 이용가능합니다.')
        return redirect('home:index')


def stat(req):
    cur_user = req.user
    cctv = Cctv.objects.all()
    cctv_list = serializers.serialize('json', cctv)

    if cur_user.is_authenticated:
        user = Profile.objects.get(user=auth.get_user(req))
        date = {}
        brand_arr = []
        brand_dic = {}
        submit_arr = []

        if req.method == 'POST':
            location = req.POST['location']
            start_time = req.POST['start_time']
            end_time = req.POST['end_time']

            date['location'] = location
            date['start_time'] = start_time
            date['end_time'] = end_time

            if (start_time > end_time):
                messages.info(req, "검색 시간을 확인해주세요.")
                return redirect("recognition:recognition")

            # print(location)

            filter_cctv = Cctv.objects.filter(location=location, start_time__lte=start_time).order_by('start_time')

            if bool(filter_cctv) == False:
                cctv_log = []
                return redirect('statistic:statistic')

            else:
                cctv_log = CctvLog.objects.filter(cctv_id=filter_cctv[0].id, appearance_time__gte=start_time,
                                                  appearance_time__lte=end_time).order_by('appearance_time')

                for i in cctv_log:
                    brand_arr.append(i.car_model.brand)

                for i in brand_arr:
                    try: brand_dic[i] += 1
                    except: brand_dic[i] = 1

                for i in brand_dic.keys():
                    temp_dic = {}
                    temp_dic['brand'] = i
                    temp_dic['car_count'] = brand_dic[i]
                    submit_arr.append(temp_dic)

            if not cctv_log:
                messages.info(req, "검색된 데이터가 존재하지 않습니다.")

        return render(req, "statistic_Service.html", {'user': user, 'cctv': cctv_list, 'count': range(cctv.count()), 'dataset': submit_arr, 'date': date})

    else:
        messages.info(req, '로그인 후 이용가능합니다.')
        return redirect('home:index')

statistic/templates/statistic_Service.html
{% for i in test %}
    {{ i.car_model.brand }}
{% endfor %}
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title>커피탄 리 : 차량 통계</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/graph.css' %}">
    <link rel="stylesheet" href="{% static 'css/service.css' %}">
    <link rel="stylesheet" href="{% static 'css/button.css' %}">
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css" rel="stylesheet">
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
    <script src="http://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">

</head>

<style>
    .textbox{
        width: 150px;
        height: 31px;
        text-align: center;
    }
</style>

<body>

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <script>alert("{{ message }}")</script>
        {% endfor %}
    </ul>
{% endif %}

{% include 'nav.html' %}
<br>
<div class="container">
    <div class="row search-sec" style="text-align: center">
         <label>위치: </label>&nbsp;&nbsp;<input class="textbox" type="text" readonly placeholder="{{ date.location }}">&nbsp;&nbsp;
        <label>시작시간: </label>&nbsp;&nbsp;<input class="textbox" type="text" readonly placeholder="{{ date.start_time }}">&nbsp;&nbsp;
        <label>종료시간: </label>&nbsp;&nbsp;<input class="textbox" type="text" readonly placeholder="{{ date.end_time }}">&nbsp;&nbsp;&nbsp;&nbsp;
        <a class="themeBtn" id="tab_button" style="width: 100px" data-target="#statisticModal"
                                 data-toggle="modal" onclick="setlayout()">검색하기</a>
    </div>
</div>
<br>
<div class="container">
    <div class="col-lg-2 menu" style="text-align: center;">
        <h3>MENU</h3>
        {% if dataset %}
            <div>
                <form action="{% url 'recognition:recog' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="start_time" value="{{ date.start_time }}">
                    <input type="hidden" name="end_time" value="{{ date.end_time }}">
                    <input type="hidden" name="location" value="{{ date.location }}">

                    <button class="themeBtn" id="tab_button" style="color: black;" type="submit;">
                        <i class="fa fa-car fa-lg" style="margin-right: 5px;"></i>
                        <span style="margin-right: 15px;">Go Recognition</span></button>

                </form>
            </div>
        {% else %}
            <a class="themeBtn" href="{% url 'recognition:recognition' %}" id="tab_button" style="color: black;">
                <i class="fa fa-car fa-lg" style="margin-right: 5px;"></i>Go Recognition</a>
            <br>
        {% endif %}

    </div>

    <div style="text-align:center;">
            <div class="col-lg-10" style="text-align:center;height: 500px;position: relative;">

                {% if dataset %}
                    <script src="https://code.highcharts.com/highcharts.src.js"></script>
                    <div id="graph" style="width:75%;height:100%;margin:20px;"></div>
                    <script>
                        Highcharts.chart('graph', {
                            chart: {
                                type: 'column'
                            },
                            title: {
                                text: '지나간 차 종류'
                            },
                            xAxis: {
                                categories: ['지나간 차'],
                            },

                            series: [
                                {% for entry in dataset %}
                                {
                                    name: '{{ entry.brand }}',
                                    data: [{{ entry.car_count }}],
                                    color: '{{ loop.index }}'
                                },
                                {% if not forloop.last %}{% endif %}{% endfor %}
                            ]
                        });
                    </script>
                {% else %}
                    <div id="page1">
                        <button id="btn_page2" class="btn" onclick="page2_show()"
                                style="position: absolute;right: 0px;height: 100%;opacity: 0%;width:50%;">다음
                        </button>

                <img style="width: auto;height: auto;max-width: 100%;max-height: 470px;" src="{% static 'images/stat_menual1.png' %}">
                    </div>
                    <div id="page2" style="display: none;">
                        <button id="btn_page1" class="btn" onclick="page1_show()"
                                style="position: absolute;left: 0px;height: 100%;opacity: 0%;width:50%;">이전
                        </button>
                        <button id="btn_page3" class="btn" onclick="page3_show()"
                                style="position: absolute;right: 0px;height: 100%;opacity: 0%;width:50%;">다음
                        </button>

                <img style="width: auto;height: auto;max-width: 100%;max-height: 470px;" src="{% static 'images/stat_menual2.png' %}">
                    </div>
                    <div id="page3" style="display: none">
                        <button id="btn_page2" class="btn" onclick="page2_show()"
                                style="position: absolute;left: 0px;height: 100%;opacity: 0%;width:50%;">이전
                        </button>

                <img style="width: auto;height: auto;max-width: 100%;max-height: 470px;" src="{% static 'images/stat_menual3.png' %}">
                    </div>

                    <div style="position: absolute;left:0px; bottom: -15px;width: 100%">
                        <input class = radiobtn id="radio_page1" type="radio" name="page" value="1" checked="checked"
                               onclick="page1_show()">
                        <input class = radiobtn id="radio_page2" type="radio" name="page" value="2" onclick="page2_show()">
                        <input class = radiobtn id="radio_page3" type="radio" name="page" value="3" onclick="page3_show()">

                        <script>
                            page1 = document.getElementById("page1");
                            page2 = document.getElementById("page2");
                            page3 = document.getElementById("page3");

                            function page1_show() {
                                page2.style.display = "none";
                                page3.style.display = "none";

                                $('#radio_page1').prop('checked', true);
                                page1.style.display = "block";
                            }

                            function page2_show() {
                                page1.style.display = "none";
                                page3.style.display = "none";


                                $('#radio_page2').prop('checked', true);
                                page2.style.display = "block";
                            }

                            function page3_show() {
                                page1.style.display = "none";
                                page2.style.display = "none";

                                $('#radio_page3').prop('checked', true);
                                page3.style.display = "block";
                            }
                        </script>
                    </div>
                {% endif %}
            </div>

    </div>
</div>

<br>
{% include 'statistic_modal.html' %}
{% include 'footer.html' %}

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=a8a08365e71499493906a12ac8f92432"></script>
<script>
    var statistic_container = document.getElementById('statistic_map');

    var options = {
        center: new kakao.maps.LatLng(37.549341, 127.0742582),
        level: 3
    };

    var statistic_map = new kakao.maps.Map(statistic_container, options);

    function setlayout() {
        setTimeout(function () {
                statistic_map.relayout();
            }
            , 0);
    }

    var cctv_obj = "{{ cctv }}".replace(/&quot;/g, '"');
    var cctv_json = JSON.parse(cctv_obj);

    // 마커 이미지의 이미지 주소입니다
    var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png";

    var positions = [
        {% for i in count %}
            {
                title: cctv_json[{{i}}].fields.location,
                latlng: new kakao.maps.LatLng(cctv_json[{{i}}].fields.latitude, cctv_json[{{i}}].fields.longtitude)
            },
        {% endfor %}
    ];

    for (var i = 0; i < positions.length; i++) {

        var imageSize = new kakao.maps.Size(24, 35);

        // 마커를 생성합니다
        var statistic_marker = new kakao.maps.Marker({
            map: statistic_map, // 마커를 표시할 지도
            position: positions[i].latlng, // 마커를 표시할 위치
            title: positions[i].title, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다
            clickable: true
        });

        var infowindow = new kakao.maps.InfoWindow({
            content: positions[i].title // 인포윈도우에 표시할 내용
        });

        kakao.maps.event.addListener(statistic_marker, 'click', get_location(positions[i].title));
        kakao.maps.event.addListener(statistic_marker, 'mouseover', makeOverListener(statistic_map, statistic_marker, infowindow));
        kakao.maps.event.addListener(statistic_marker, 'mouseout', makeOutListener(infowindow));

    }

    // 인포윈도우를 표시하는 클로저를 만드는 함수입니다
    function makeOverListener(map, marker, infowindow) {
        return function () {
            infowindow.open(map, marker);
        };
    }

    // 인포윈도우를 닫는 클로저를 만드는 함수입니다
    function makeOutListener(infowindow) {
        return function () {
            infowindow.close();
        };
    }

    function get_location(info) {
        return function () {
            document.getElementById("statistic_location").value = info;
        };
    }

    $(function () {
        $('#statistic_start_time').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            ignoreReadonly: true
        });
    });

    $(function () {
        $('#statistic_end_time').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            ignoreReadonly: true
        });
    });

</script>
</body>
</html>